[package]
name = "AI"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
hyper = { version = "^0.14", features = ["full"]}
hyper-tls = "^0.5"
tokio = { version = "1", features = ["full"]}
serde = "^1"
serde_derive = "^1"
serde_json = "^1"
spinners = "^2"